# action.yml
name: 'Json to Excel'
description: 'Greet someone and record the time'
inputs:
  zap:  # id of input
    description: 'Path to zap'
    required: true
    default: 'report_json.json'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}